using Fidelizar.Domain.Entities;

namespace Fidelizar.Application.Services;

/// <param name="NegocioId">Required, not a convention (I8).</param>
/// <param name="MovimientoId">The movement being corrected.</param>
/// <param name="Motivo">Mandatory — every <c>Ajuste</c> needs one (I3).</param>
/// <param name="UsuarioId">Who is voiding it. Required: an <c>Ajuste</c> always has a real actor
/// (Encargada/Dueño only, FUNCTIONAL-SPEC §8).</param>
/// <param name="Hoy">When the void itself happens — the new <c>Ajuste</c> row's own
/// <c>FechaEfectiva</c>, independent of the original movement's date.</param>
/// <param name="ClaveIdempotencia">
/// Generated by the client, one per void attempt (README decision #6, extended to S8 2026-08-21).
/// A retry after a lost response reuses the same key so the second POST is recognised as the same
/// attempt instead of writing a second <c>Ajuste</c>.
/// </param>
public sealed record AnularMovimientoRequest(
    int NegocioId, long MovimientoId, string Motivo, int UsuarioId, DateOnly Hoy, string ClaveIdempotencia);

/// <summary>
/// S8 Anular movimiento (FUNCTIONAL-SPEC §8) — the UI surface of I1/I3. There is no edit and no
/// delete anywhere in this product: voiding movement <c>M</c> writes a new <c>Ajuste</c> of
/// <c>-M.Monto</c>. Both rows stay in the ledger forever.
/// </summary>
public interface IAnulacionMovimientoService
{
    /// <summary>
    /// Writes the correcting <c>Ajuste</c>. Idempotent on
    /// <see cref="AnularMovimientoRequest.ClaveIdempotencia"/>: a call reusing a key already on
    /// record, for the same movement and reason, returns the original <c>Ajuste</c> — no second
    /// row, no error. The same key with different data is a client mistake, not a retry.
    /// </summary>
    /// <exception cref="Fidelizar.Domain.Exceptions.EntityNotFoundException">
    /// No movement with that id exists for this business — including one that belongs to a
    /// different <c>NegocioId</c> (I8: never distinguished from "does not exist" in the response).
    /// </exception>
    /// <exception cref="Fidelizar.Domain.Exceptions.ValidationException">
    /// <c>ClaveIdempotencia</c> is missing or blank (<c>CLAVE_IDEMPOTENCIA_REQUERIDA</c>).
    /// </exception>
    /// <exception cref="Fidelizar.Domain.Exceptions.ConflictException">
    /// <c>ClaveIdempotencia</c> was already used for a different void
    /// (<c>CLAVE_IDEMPOTENCIA_REUTILIZADA</c>).
    /// </exception>
    Task<MovimientoCredito> AnularAsync(
        AnularMovimientoRequest request, CancellationToken cancellationToken = default);
}
