using Fidelizar.Domain.Entities;

namespace Fidelizar.Application.Services;

/// <summary>What the caller supplies to register a redemption (RN-05, RN-24).</summary>
/// <param name="NegocioId">Required, not a convention (I8).</param>
/// <param name="MiembroId">The member redeeming.</param>
/// <param name="Monto">Positive. The service stores it as a negative movement.</param>
/// <param name="Motivo">Mandatory for every <c>Canje</c> (DATA-MODEL §4).</param>
/// <param name="UsuarioId">Who is registering it. Null only for <c>sistema</c>.</param>
/// <param name="FechaEfectiva">When the redemption actually happened — may be in the past
/// (a power-cut redemption written on paper and loaded later, ARCHITECTURE §10).</param>
/// <param name="Hoy">Today's date, used to decide whether <paramref name="FechaEfectiva"/> is
/// retroactive. Passed in rather than read from the clock so this is testable without one.</param>
/// <param name="ClaveIdempotencia">
/// Generated by the client, one per attempt — not one per logical redemption (README decision
/// #6, 2026-08-19). A retry after a lost response reuses the same key so the second POST is
/// recognised as the same attempt instead of writing a second <c>Canje</c>.
/// </param>
public sealed record RegistrarCanjeRequest(
    int NegocioId,
    int MiembroId,
    decimal Monto,
    string Motivo,
    int? UsuarioId,
    DateOnly FechaEfectiva,
    DateOnly Hoy,
    string ClaveIdempotencia);

public interface ISaldoService
{
    /// <summary>The member's balance: <c>SUM(Monto)</c> of their movements (I2).</summary>
    /// <exception cref="Fidelizar.Domain.Exceptions.EntityNotFoundException">
    /// No member with <paramref name="miembroId"/> exists for this business — including one that
    /// belongs to a different <c>NegocioId</c> (I8). <c>SUM(Monto)</c> over zero rows is also 0,
    /// so this lookup is the only thing that can tell an unknown id apart from a member whose
    /// balance is genuinely zero.
    /// </exception>
    Task<decimal> ObtenerSaldoAsync(int negocioId, int miembroId, CancellationToken cancellationToken = default);

    /// <summary>
    /// Registers a redemption. Rejects any amount above the available balance (I6, RN-24) and
    /// blocks every redemption outright while the balance is negative (RN-25) — that state is
    /// recovered only by a system-generated <c>Ajuste</c>, never by a human redemption.
    ///
    /// <para>
    /// Idempotent on <see cref="RegistrarCanjeRequest.ClaveIdempotencia"/> (README decision #6,
    /// 2026-08-19): a call reusing a key already recorded, with the same member/amount/date/reason,
    /// returns the original movement — no second row, no error. The same key with different data
    /// is a client mistake, not a retry, and is rejected.
    /// </para>
    /// </summary>
    /// <exception cref="Fidelizar.Domain.Exceptions.ConflictException">
    /// <paramref name="request"/>'s <c>ClaveIdempotencia</c> was already used for a different
    /// member, amount, date or reason (<c>CLAVE_IDEMPOTENCIA_REUTILIZADA</c>).
    /// </exception>
    Task<MovimientoCredito> RegistrarCanjeAsync(
        RegistrarCanjeRequest request, CancellationToken cancellationToken = default);
}
