using System.ComponentModel.DataAnnotations;

namespace Fidelizar.Shared.Movimientos;

/// <summary>S8 Anular movimiento request body. <c>Motivo</c> is mandatory client-side as a fast
/// hint; the real enforcement is <c>MovimientoCredito.Crear</c>'s own check on every
/// <c>Ajuste</c> (I3), server-side, regardless of this attribute.
///
/// <c>ClaveIdempotencia</c> is generated by the client, one per void attempt, and kept across a
/// retry after a lost response — same contract as S4's <c>RegistrarCanjeRequest</c> (README
/// decision #6, extended to this endpoint 2026-08-21). Without it a dropped connection cannot be
/// told apart from a lost response, and the retry writes a second <c>Ajuste</c>.</summary>
public sealed record AnularMovimientoRequest(
    [Required(ErrorMessage = "El motivo es obligatorio.")]
    string Motivo,
    // No `property:` target: MVC binds a positional record through its constructor and reads
    // validation metadata off the parameter. Moving these to the property makes it throw on every
    // request to this endpoint.
    [Required(ErrorMessage = "La clave de idempotencia es obligatoria.")]
    [StringLength(100, ErrorMessage = "La clave de idempotencia no puede superar los 100 caracteres.")]
    string ClaveIdempotencia);
