// <auto-generated />
using System;
using Fidelizar.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Fidelizar.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FidelizarDbContext))]
    partial class FidelizarDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Fidelizar.Domain.Entities.ConfiguracionPrograma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CreadoPorUsuarioId")
                        .HasColumnType("integer");

                    b.Property<bool>("GraciaHabilitada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int?>("MesesDeGracia")
                        .HasColumnType("integer");

                    b.Property<int>("NegocioId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("ObjetivoMensual")
                        .HasColumnType("numeric(14,2)");

                    b.Property<decimal>("PorcentajeAcumulacion")
                        .HasColumnType("numeric(5,4)");

                    b.Property<int?>("TopeMesesCongelados")
                        .HasColumnType("integer");

                    b.Property<decimal?>("UmbralMesMalo")
                        .HasColumnType("numeric(14,2)");

                    b.Property<DateOnly>("VigenteDesde")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("VigenteHasta")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "NegocioId" }, "IX_ConfiguracionesPrograma_NegocioId");

                    b.HasIndex(new[] { "NegocioId" }, "IX_ConfiguracionesPrograma_NegocioId_Vigente")
                        .IsUnique()
                        .HasFilter("\"VigenteHasta\" IS NULL");

                    b.ToTable("ConfiguracionesPrograma", (string)null);
                });

            modelBuilder.Entity("Fidelizar.Domain.Entities.Consentimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Canal")
                        .HasColumnType("integer");

                    b.Property<int>("MiembroId")
                        .HasColumnType("integer");

                    b.Property<int>("NegocioId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OcurridoEn")
                        .HasColumnType("timestamptz");

                    b.Property<bool>("Otorgado")
                        .HasColumnType("boolean");

                    b.Property<int?>("RegistradoPorUsuarioId")
                        .HasColumnType("integer");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<string>("VersionTexto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NegocioId");

                    b.HasIndex("MiembroId", "Tipo");

                    b.ToTable("Consentimientos", (string)null);
                });

            modelBuilder.Entity("Fidelizar.Domain.Entities.Corte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DeclaradoEn")
                        .HasColumnType("timestamptz");

                    b.Property<int>("DeclaradoPorUsuarioId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<int>("NegocioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NegocioId")
                        .IsUnique();

                    b.ToTable("Cortes", (string)null);
                });

            modelBuilder.Entity("Fidelizar.Domain.Entities.Miembro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ActualizadoEn")
                        .HasColumnType("timestamptz");

                    b.Property<string>("ClienteExternoId")
                        .HasColumnType("text");

                    b.Property<string>("Dni")
                        .HasColumnType("text");

                    b.Property<DateOnly>("FechaAlta")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<int>("NegocioId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NombreNormalizado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NumeroSocio")
                        .HasColumnType("text");

                    b.Property<int?>("SucursalId")
                        .HasColumnType("integer");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NegocioId");

                    b.HasIndex("NombreNormalizado");

                    b.HasIndex("NegocioId", "ClienteExternoId")
                        .IsUnique()
                        .HasFilter("\"ClienteExternoId\" IS NOT NULL");

                    b.ToTable("Miembros", (string)null);
                });

            modelBuilder.Entity("Fidelizar.Domain.Entities.MovimientoCredito", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<int?>("ConfiguracionId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("FechaEfectiva")
                        .HasColumnType("date");

                    b.Property<int>("MiembroId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Monto")
                        .HasColumnType("numeric(14,2)");

                    b.Property<string>("Motivo")
                        .HasColumnType("text");

                    b.Property<int>("NegocioId")
                        .HasColumnType("integer");

                    b.Property<string>("Periodo")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("char(7)")
                        .IsFixedLength();

                    b.Property<string>("ReferenciaVenta")
                        .HasColumnType("text");

                    b.Property<DateTime>("RegistradoEn")
                        .HasColumnType("timestamptz");

                    b.Property<decimal>("SaldoResultante")
                        .HasColumnType("numeric(14,2)");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NegocioId", "MiembroId");

                    b.HasIndex("NegocioId", "Periodo");

                    b.HasIndex("NegocioId", "MiembroId", "Tipo", "ReferenciaVenta")
                        .IsUnique()
                        .HasDatabaseName("IX_MovimientosCredito_Acumulacion_Unica")
                        .HasFilter("\"Tipo\" = 1");

                    b.ToTable("MovimientosCredito", (string)null);
                });

            modelBuilder.Entity("Fidelizar.Domain.Entities.Negocio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Cuit")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Negocios", (string)null);
                });

            modelBuilder.Entity("Fidelizar.Domain.Entities.RegistroAuditoria", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Detalle")
                        .HasColumnType("jsonb");

                    b.Property<int?>("EntidadId")
                        .HasColumnType("integer");

                    b.Property<string>("EntidadTipo")
                        .HasColumnType("text");

                    b.Property<int>("NegocioId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OcurridoEn")
                        .HasColumnType("timestamptz");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NegocioId");

                    b.HasIndex("NegocioId", "UsuarioId");

                    b.ToTable("RegistrosAuditoria", (string)null);
                });

            modelBuilder.Entity("Fidelizar.Domain.Entities.Sucursal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<string>("CodigoExterno")
                        .HasColumnType("text");

                    b.Property<int>("NegocioId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NegocioId");

                    b.ToTable("Sucursales", (string)null);
                });

            modelBuilder.Entity("Fidelizar.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<int>("NegocioId")
                        .HasColumnType("integer");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Rol")
                        .HasColumnType("integer");

                    b.Property<int?>("SucursalId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NegocioId");

                    b.HasIndex("NegocioId", "Email")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
